"""created DB rooms, users, bookings

Revision ID: 9e73a767bcf3
Revises: 4c3422c7b7be
Create Date: 2025-10-22 21:26:14.305059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e73a767bcf3'
down_revision: Union[str, Sequence[str], None] = '4c3422c7b7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
